### ISSUE TITLE
Check paths in oc apply command

### ISSUE THREAD

**Issue by cwilkers** [open-cluster-management/labs#12]
In multicloud-deployment/labs/6.md a command is given to deploy the app,

```bash
cd assets/app/acm
oc --context hub apply -f .
```

This doesn't match the repo as it is.

After cloning, the path would be `labs/multicloud-deployment/acm`

**Comment by iranzo** [comment]
@jparrill this should be closed as per #16

**Comment by cwilkers** [comment]
I should have closed after merge :-)
